/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_tylercruz;

import javax.swing.DefaultListModel;

/**
 *
 * @author Tyler C
 */
public class Main_Lab7 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Lab7
     */
    public Main_Lab7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CrearCarro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        JT_NumeroPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JSpinner_DoorCant = new javax.swing.JSpinner();
        CB_Size = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JSpinner_LevelDirty = new javax.swing.JSpinner();
        JB_CreateCarro = new javax.swing.JButton();
        JD_CrearCliente = new javax.swing.JDialog();
        MainPanel_CrearCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JT_NameCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JT_ApellidoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JSpinner_edadCliente = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        JList_CarrosCliente = new javax.swing.JList<>();
        JB_SaveCliente = new javax.swing.JButton();
        JD_RegistrarEmpleado = new javax.swing.JDialog();
        MainPanel_RegistrarEmpleado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JT_NameEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JT_ApellidoEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JSpinner_Empleado = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        JList_CarrosEmpleado = new javax.swing.JList<>();
        JB_SaveEmpleado = new javax.swing.JButton();
        MainPanel_JFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_CreateCar = new javax.swing.JMenuItem();
        JMI_CreateClient = new javax.swing.JMenuItem();
        JMI_CreateEmployee = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Numero Placa: ");

        jLabel2.setText("Size: ");

        JSpinner_DoorCant.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));

        CB_Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande", " " }));

        jLabel3.setText("Numeros Puerta");

        jLabel4.setText("Nivel de sucio");

        JSpinner_LevelDirty.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        JB_CreateCarro.setText("Save");
        JB_CreateCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CreateCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearCarroLayout = new javax.swing.GroupLayout(JD_CrearCarro.getContentPane());
        JD_CrearCarro.getContentPane().setLayout(JD_CrearCarroLayout);
        JD_CrearCarroLayout.setHorizontalGroup(
            JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSpinner_DoorCant, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_NumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSpinner_LevelDirty, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_CreateCarro))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        JD_CrearCarroLayout.setVerticalGroup(
            JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_NumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CB_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSpinner_DoorCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JSpinner_LevelDirty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_CreateCarro)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido: ");

        jLabel7.setText("Edad: ");

        JSpinner_edadCliente.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        JList_CarrosCliente.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(JList_CarrosCliente);

        JB_SaveCliente.setText("Save");

        javax.swing.GroupLayout MainPanel_CrearClienteLayout = new javax.swing.GroupLayout(MainPanel_CrearCliente);
        MainPanel_CrearCliente.setLayout(MainPanel_CrearClienteLayout);
        MainPanel_CrearClienteLayout.setHorizontalGroup(
            MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                        .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JT_NameCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(JT_ApellidoCliente))
                            .addComponent(JSpinner_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_SaveCliente)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        MainPanel_CrearClienteLayout.setVerticalGroup(
            MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JT_NameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JT_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JSpinner_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_SaveCliente)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CrearClienteLayout = new javax.swing.GroupLayout(JD_CrearCliente.getContentPane());
        JD_CrearCliente.getContentPane().setLayout(JD_CrearClienteLayout);
        JD_CrearClienteLayout.setHorizontalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_CrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CrearClienteLayout.setVerticalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_CrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido: ");

        jLabel10.setText("Edad: ");

        JSpinner_Empleado.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        JList_CarrosEmpleado.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(JList_CarrosEmpleado);

        JB_SaveEmpleado.setText("Save");

        javax.swing.GroupLayout MainPanel_RegistrarEmpleadoLayout = new javax.swing.GroupLayout(MainPanel_RegistrarEmpleado);
        MainPanel_RegistrarEmpleado.setLayout(MainPanel_RegistrarEmpleadoLayout);
        MainPanel_RegistrarEmpleadoLayout.setHorizontalGroup(
            MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JT_NameEmpleado)
                        .addComponent(JT_ApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JSpinner_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_SaveEmpleado)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        MainPanel_RegistrarEmpleadoLayout.setVerticalGroup(
            MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JT_NameEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JT_ApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JSpinner_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_SaveEmpleado)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_RegistrarEmpleadoLayout = new javax.swing.GroupLayout(JD_RegistrarEmpleado.getContentPane());
        JD_RegistrarEmpleado.getContentPane().setLayout(JD_RegistrarEmpleadoLayout);
        JD_RegistrarEmpleadoLayout.setHorizontalGroup(
            JD_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_RegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_RegistrarEmpleadoLayout.setVerticalGroup(
            JD_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_RegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable5);

        javax.swing.GroupLayout MainPanel_JFrameLayout = new javax.swing.GroupLayout(MainPanel_JFrame);
        MainPanel_JFrame.setLayout(MainPanel_JFrameLayout);
        MainPanel_JFrameLayout.setHorizontalGroup(
            MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        MainPanel_JFrameLayout.setVerticalGroup(
            MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel_JFrameLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jMenu1.setText("Creacion");

        JMI_CreateCar.setText("Creacion de Carros");
        JMI_CreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateCarActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateCar);

        JMI_CreateClient.setText("Creacion de Clientes");
        JMI_CreateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateClientActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateClient);

        JMI_CreateEmployee.setText("Creacion de Empleados");
        JMI_CreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateEmployee);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_JFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CreateCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CreateCarroActionPerformed
        // TODO add your handling code here:
        //String numeroPlaca, String size, String numeroDoors, String clean
        Carro x = new Carro(JT_NumeroPlaca.getText(),CB_Size.getSelectedItem().toString(),JSpinner_DoorCant.getValue().toString(),
        JSpinner_LevelDirty.toString());
        DefaultListModel modelo
                = (DefaultListModel) JList_CarrosCliente.getModel();
        DefaultListModel modelo1
                = (DefaultListModel) JList_CarrosEmpleado.getModel();

        modelo.addElement(x);
        modelo1.addElement(x);
        JList_CarrosCliente.setModel(modelo);
        JT_NumeroPlaca.setText("");
        JSpinner_DoorCant.setValue(2);
        JSpinner_LevelDirty.setValue(5);
    }//GEN-LAST:event_JB_CreateCarroActionPerformed

    private void JMI_CreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateCarActionPerformed
        // TODO add your handling code here:
        JD_CrearCarro.setModal(true);
        JD_CrearCarro.pack();
        JD_CrearCarro.setLocationRelativeTo(this);
        JD_CrearCarro.setVisible(true);
    }//GEN-LAST:event_JMI_CreateCarActionPerformed

    private void JMI_CreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateClientActionPerformed
        // TODO add your handling code here:
        JD_CrearCliente.setModal(true);
        JD_CrearCliente.pack();
        JD_CrearCliente.setLocationRelativeTo(this);
        JD_CrearCliente.setVisible(true);
    }//GEN-LAST:event_JMI_CreateClientActionPerformed

    private void JMI_CreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateEmployeeActionPerformed
        // TODO add your handling code here:
        JD_RegistrarEmpleado.setModal(true);
        JD_RegistrarEmpleado.pack();
        JD_RegistrarEmpleado.setLocationRelativeTo(this);
        JD_RegistrarEmpleado.setVisible(true);
        
    }//GEN-LAST:event_JMI_CreateEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Lab7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Size;
    private javax.swing.JButton JB_CreateCarro;
    private javax.swing.JButton JB_SaveCliente;
    private javax.swing.JButton JB_SaveEmpleado;
    private javax.swing.JDialog JD_CrearCarro;
    private javax.swing.JDialog JD_CrearCliente;
    private javax.swing.JDialog JD_RegistrarEmpleado;
    private javax.swing.JList<String> JList_CarrosCliente;
    private javax.swing.JList<String> JList_CarrosEmpleado;
    private javax.swing.JMenuItem JMI_CreateCar;
    private javax.swing.JMenuItem JMI_CreateClient;
    private javax.swing.JMenuItem JMI_CreateEmployee;
    private javax.swing.JSpinner JSpinner_DoorCant;
    private javax.swing.JSpinner JSpinner_Empleado;
    private javax.swing.JSpinner JSpinner_LevelDirty;
    private javax.swing.JSpinner JSpinner_edadCliente;
    private javax.swing.JTextField JT_ApellidoCliente;
    private javax.swing.JTextField JT_ApellidoEmpleado;
    private javax.swing.JTextField JT_NameCliente;
    private javax.swing.JTextField JT_NameEmpleado;
    private javax.swing.JTextField JT_NumeroPlaca;
    private javax.swing.JPanel MainPanel_CrearCliente;
    private javax.swing.JPanel MainPanel_JFrame;
    private javax.swing.JPanel MainPanel_RegistrarEmpleado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
