/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_tylercruz;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tyler C
 */
public class Main_Lab7 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Lab7
     */
    public Main_Lab7() {
        initComponents();
        TH1 = new Thread1(JProgressBar_Empleado1);
        TH2 = new Thread2(JProgressBar_Empleado2);
        TH3 = new Thread3(JProgressBar_Empleado3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CrearCarro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        JT_NumeroPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JSpinner_DoorCant = new javax.swing.JSpinner();
        CB_Size = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JSpinner_LevelDirty = new javax.swing.JSpinner();
        JB_CreateCarro = new javax.swing.JButton();
        JD_CrearCliente = new javax.swing.JDialog();
        MainPanel_CrearCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JT_NameCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JT_ApellidoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JSpinner_edadCliente = new javax.swing.JSpinner();
        JB_SaveCliente = new javax.swing.JButton();
        JD_RegistrarEmpleado = new javax.swing.JDialog();
        MainPanel_RegistrarEmpleado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JT_NameEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JT_ApellidoEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JSpinner_Empleado = new javax.swing.JSpinner();
        JB_SaveEmpleado = new javax.swing.JButton();
        JD_AddCarsToClient = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        CB_Clientes = new javax.swing.JComboBox<>();
        JB_AddingCarToClient = new javax.swing.JButton();
        CB_CarsToBeAdded = new javax.swing.JComboBox<>();
        JB_FinishCliente = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        JD_AddClienteCarsToEmployee = new javax.swing.JDialog();
        MainPanel = new javax.swing.JPanel();
        CB_CarsToEmployee = new javax.swing.JComboBox<>();
        CB_CarOwners = new javax.swing.JComboBox<>();
        CB_CARS = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JB_SaveToEmployee = new javax.swing.JButton();
        MainPanel_JFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        JProgressBar_Empleado1 = new javax.swing.JProgressBar();
        JProgressBar_Empleado2 = new javax.swing.JProgressBar();
        JProgressBar_Empleado3 = new javax.swing.JProgressBar();
        CB_Empleado1 = new javax.swing.JComboBox<>();
        CB_Empleado2 = new javax.swing.JComboBox<>();
        CB_Empleado3 = new javax.swing.JComboBox<>();
        JB_Simulacion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_CreateCar = new javax.swing.JMenuItem();
        JMI_CreateClient = new javax.swing.JMenuItem();
        JMI_CreateEmployee = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMI_AddingCarTooClient = new javax.swing.JMenuItem();
        JMI_AddingCarToEmployee = new javax.swing.JMenuItem();

        jLabel1.setText("Numero Placa: ");

        jLabel2.setText("Size: ");

        JSpinner_DoorCant.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));

        CB_Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande", " " }));

        jLabel3.setText("Numeros Puerta");

        jLabel4.setText("Nivel de sucio");

        JSpinner_LevelDirty.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        JB_CreateCarro.setText("Save");
        JB_CreateCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CreateCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearCarroLayout = new javax.swing.GroupLayout(JD_CrearCarro.getContentPane());
        JD_CrearCarro.getContentPane().setLayout(JD_CrearCarroLayout);
        JD_CrearCarroLayout.setHorizontalGroup(
            JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSpinner_DoorCant, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_NumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSpinner_LevelDirty, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_CreateCarro))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        JD_CrearCarroLayout.setVerticalGroup(
            JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCarroLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_NumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CB_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSpinner_DoorCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JSpinner_LevelDirty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_CreateCarro)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido: ");

        jLabel7.setText("Edad: ");

        JSpinner_edadCliente.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        JB_SaveCliente.setText("Save");
        JB_SaveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel_CrearClienteLayout = new javax.swing.GroupLayout(MainPanel_CrearCliente);
        MainPanel_CrearCliente.setLayout(MainPanel_CrearClienteLayout);
        MainPanel_CrearClienteLayout.setHorizontalGroup(
            MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JT_NameCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(JT_ApellidoCliente))
                            .addComponent(JSpinner_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(JB_SaveCliente)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        MainPanel_CrearClienteLayout.setVerticalGroup(
            MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_CrearClienteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JT_NameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JT_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JSpinner_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_SaveCliente)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CrearClienteLayout = new javax.swing.GroupLayout(JD_CrearCliente.getContentPane());
        JD_CrearCliente.getContentPane().setLayout(JD_CrearClienteLayout);
        JD_CrearClienteLayout.setHorizontalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearClienteLayout.createSequentialGroup()
                .addComponent(MainPanel_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_CrearClienteLayout.setVerticalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido: ");

        jLabel10.setText("Edad: ");

        JSpinner_Empleado.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        JB_SaveEmpleado.setText("Save");
        JB_SaveEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel_RegistrarEmpleadoLayout = new javax.swing.GroupLayout(MainPanel_RegistrarEmpleado);
        MainPanel_RegistrarEmpleado.setLayout(MainPanel_RegistrarEmpleadoLayout);
        MainPanel_RegistrarEmpleadoLayout.setHorizontalGroup(
            MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                        .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JT_NameEmpleado)
                                .addComponent(JT_ApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSpinner_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JB_SaveEmpleado)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        MainPanel_RegistrarEmpleadoLayout.setVerticalGroup(
            MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JT_NameEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JT_ApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JSpinner_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_SaveEmpleado)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_RegistrarEmpleadoLayout = new javax.swing.GroupLayout(JD_RegistrarEmpleado.getContentPane());
        JD_RegistrarEmpleado.getContentPane().setLayout(JD_RegistrarEmpleadoLayout);
        JD_RegistrarEmpleadoLayout.setHorizontalGroup(
            JD_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_RegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_RegistrarEmpleadoLayout.setVerticalGroup(
            JD_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_RegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JB_AddingCarToClient.setText("Add Car too Client");
        JB_AddingCarToClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddingCarToClientActionPerformed(evt);
            }
        });

        JB_FinishCliente.setText("Finish Creating Employee by adding to Archive");
        JB_FinishCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_FinishClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_FinishCliente)
                    .addComponent(JB_AddingCarToClient)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CB_Clientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CB_CarsToBeAdded, 0, 263, Short.MAX_VALUE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(CB_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_CarsToBeAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_AddingCarToClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_FinishCliente)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_AddCarsToClientLayout = new javax.swing.GroupLayout(JD_AddCarsToClient.getContentPane());
        JD_AddCarsToClient.getContentPane().setLayout(JD_AddCarsToClientLayout);
        JD_AddCarsToClientLayout.setHorizontalGroup(
            JD_AddCarsToClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_AddCarsToClientLayout.setVerticalGroup(
            JD_AddCarsToClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuItem1.setText("jMenuItem1");

        CB_CarsToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_CarsToEmployeeActionPerformed(evt);
            }
        });

        CB_CarOwners.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_CarOwnersItemStateChanged(evt);
            }
        });
        CB_CarOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_CarOwnersActionPerformed(evt);
            }
        });

        jLabel11.setText("Employee");

        jLabel12.setText("CarOwner");

        jLabel13.setText("Car");

        JB_SaveToEmployee.setText("Save To Employee");
        JB_SaveToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveToEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_SaveToEmployee)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB_CarsToEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_CarOwners, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_CARS, 0, 307, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_CarsToEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_CarOwners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_CARS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(35, 35, 35)
                .addComponent(JB_SaveToEmployee)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_AddClienteCarsToEmployeeLayout = new javax.swing.GroupLayout(JD_AddClienteCarsToEmployee.getContentPane());
        JD_AddClienteCarsToEmployee.getContentPane().setLayout(JD_AddClienteCarsToEmployeeLayout);
        JD_AddClienteCarsToEmployeeLayout.setHorizontalGroup(
            JD_AddClienteCarsToEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AddClienteCarsToEmployeeLayout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_AddClienteCarsToEmployeeLayout.setVerticalGroup(
            JD_AddClienteCarsToEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AddClienteCarsToEmployeeLayout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable5);

        JProgressBar_Empleado1.setMaximum(10);

        JProgressBar_Empleado2.setMaximum(10);

        JProgressBar_Empleado3.setMaximum(10);

        JB_Simulacion.setText("Simulacion");
        JB_Simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SimulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel_JFrameLayout = new javax.swing.GroupLayout(MainPanel_JFrame);
        MainPanel_JFrame.setLayout(MainPanel_JFrameLayout);
        MainPanel_JFrameLayout.setHorizontalGroup(
            MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                .addComponent(JProgressBar_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                        .addComponent(CB_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(CB_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                        .addComponent(JProgressBar_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JProgressBar_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_JFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CB_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Simulacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanel_JFrameLayout.setVerticalGroup(
            MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel_JFrameLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JProgressBar_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JProgressBar_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JProgressBar_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(JB_Simulacion)
                .addGap(56, 56, 56))
        );

        jMenu1.setText("Creacion");

        JMI_CreateCar.setText("Creacion de Carros");
        JMI_CreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateCarActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateCar);

        JMI_CreateClient.setText("Creacion de Clientes");
        JMI_CreateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateClientActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateClient);

        JMI_CreateEmployee.setText("Creacion de Empleados");
        JMI_CreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CreateEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CreateEmployee);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Add");

        JMI_AddingCarTooClient.setText("Add Car to Client");
        JMI_AddingCarTooClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AddingCarTooClientActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_AddingCarTooClient);

        JMI_AddingCarToEmployee.setText("Add Car to Employee");
        JMI_AddingCarToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AddingCarToEmployeeActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_AddingCarToEmployee);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel_JFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CreateCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CreateCarroActionPerformed
        // TODO add your handling code here:
        //String numeroPlaca, String size, String numeroDoors, String clean
        Carro x = new Carro(JT_NumeroPlaca.getText(), CB_Size.getSelectedItem().toString(), JSpinner_DoorCant.getValue().toString(),
                JSpinner_LevelDirty.getValue().toString());
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_CarsToBeAdded.getModel();
        modelo2.addElement(x);
        CB_CarsToBeAdded.setModel(modelo2);
        bitacora ap = new bitacora("./Carros.cbm");
        ap.cargarArchivo();
        ap.setCarro(x);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Carro guardado exitosamente");
        //JList_CarrosCliente.setModel(modelo);
        JT_NumeroPlaca.setText("");
        JSpinner_DoorCant.setValue(2);
        JSpinner_LevelDirty.setValue(5);

    }//GEN-LAST:event_JB_CreateCarroActionPerformed

    private void JMI_CreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateCarActionPerformed
        // TODO add your handling code here:
        JD_CrearCarro.setModal(true);
        JD_CrearCarro.pack();
        JD_CrearCarro.setLocationRelativeTo(this);
        JD_CrearCarro.setVisible(true);
    }//GEN-LAST:event_JMI_CreateCarActionPerformed

    private void JMI_CreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateClientActionPerformed
        // TODO add your handling code here:
        JD_CrearCliente.setModal(true);
        JD_CrearCliente.pack();
        JD_CrearCliente.setLocationRelativeTo(this);
        JD_CrearCliente.setVisible(true);
    }//GEN-LAST:event_JMI_CreateClientActionPerformed

    private void JMI_CreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CreateEmployeeActionPerformed
        // TODO add your handling code here:
        JD_RegistrarEmpleado.setModal(true);
        JD_RegistrarEmpleado.pack();
        JD_RegistrarEmpleado.setLocationRelativeTo(this);
        JD_RegistrarEmpleado.setVisible(true);

    }//GEN-LAST:event_JMI_CreateEmployeeActionPerformed

    private void JB_SaveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveClienteActionPerformed
        // TODO add your handling code here:
        //String nombre, String apellido, String edad
        Cliente x = new Cliente(this.JT_NameCliente.getText(), this.JT_ApellidoCliente.getText(),
                this.JSpinner_edadCliente.getValue().toString());
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_Clientes.getModel();
        modelo2.addElement(x);
        CB_Clientes.setModel(modelo2);

        //x.setListCarros(this.JList_CarrosCliente.getSele);
        bitacora1 ap = new bitacora1("./Cliente.cbm");
        ap.cargarArchivo();
        ap.setCliente(x);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
    }//GEN-LAST:event_JB_SaveClienteActionPerformed

    private void JB_SaveEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveEmpleadoActionPerformed
        // TODO add your handling code here:
        if (cont < 3) {
            Empleado x = new Empleado(this.JT_NameEmpleado.getText(), this.JT_ApellidoEmpleado.getText(),
                    this.JSpinner_Empleado.getValue().toString());
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_CarsToEmployee.getModel();
            modelo2.addElement(x);
            CB_CarsToEmployee.setModel(modelo2);
            //Separator
            bitacora2 ap = new bitacora2("./Empleado.cbm");
            ap.cargarArchivo();
            ap.setEmpleado(x);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Empleado guardado exitosamente");
            cont++;
        } else {
            JOptionPane.showMessageDialog(this, "Sorry already reached limit of employees! No more can be created!");
        }
    }//GEN-LAST:event_JB_SaveEmpleadoActionPerformed

    private void JMI_AddingCarTooClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AddingCarTooClientActionPerformed
        // TODO add your handling code here:
        JD_AddCarsToClient.setModal(true);
        JD_AddCarsToClient.pack();
        JD_AddCarsToClient.setLocationRelativeTo(this);
        JD_AddCarsToClient.setVisible(true);

    }//GEN-LAST:event_JMI_AddingCarTooClientActionPerformed

    private void JB_AddingCarToClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddingCarToClientActionPerformed
        // TODO add your handling code here:
        Cliente temp
                = (Cliente) CB_Clientes.getSelectedItem();
        if (temp != null) {
            Carro temp1
                    = (Carro) CB_CarsToBeAdded.getSelectedItem();
            temp.setCarro(temp1);
            JOptionPane.showMessageDialog(this, "Added to  client successfully!");
            if (temp1 != null) {
                temp.setCarro(temp1);
            }

        }

    }//GEN-LAST:event_JB_AddingCarToClientActionPerformed

    private void CB_CarsToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_CarsToEmployeeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CB_CarsToEmployeeActionPerformed

    private void JMI_AddingCarToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AddingCarToEmployeeActionPerformed
        // TODO add your handling code here:
        JD_AddClienteCarsToEmployee.setModal(true);
        JD_AddClienteCarsToEmployee.pack();
        JD_AddClienteCarsToEmployee.setLocationRelativeTo(this);
        JD_AddClienteCarsToEmployee.setVisible(true);
    }//GEN-LAST:event_JMI_AddingCarToEmployeeActionPerformed

    private void JB_FinishClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_FinishClienteActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you want to save Cliente", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // yes option
            bitacora1 ap = new bitacora1("./Cliente.cbm");
            ap.cargarArchivo();
            ap.setCliente((Cliente) CB_Clientes.getSelectedItem());
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");

        } else {
            // no option
        }
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_CarOwners.getModel();
        modelo2.addElement((Cliente) CB_Clientes.getSelectedItem());
        CB_CarOwners.setModel(modelo2);
    }//GEN-LAST:event_JB_FinishClienteActionPerformed

    private void CB_CarOwnersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_CarOwnersItemStateChanged
        // TODO add your handling code here:
//        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_CARS.getModel();
//        Cliente temp
//                = (Cliente) CB_CarOwners.getSelectedItem();
//        if (temp != null) {
//            System.out.println("HELLLOO  ONE");
//            bitacora1 ap = new bitacora1("./Cliente.cbm");
//            ap.cargarArchivo();
////            DefaultComboBoxModel modelo
////                        = new DefaultComboBoxModel( 
////                                ap.getListaClientes().toArray());
//            for (int i = 0; i < ap.getListaClientes().size(); i++) {
//                System.out.println("IS IT HERE");
//                if (temp.equals(ap.getListaClientes().get(i))) {
//                    //System.out.println("HELLOOOOO");
//                    //ap.getListaClientes().get(i).getListCarros();
//                    for (int j = 0; j < ap.getListaClientes().get(i).getListCarros().size(); j++) {
//                        modelo2.addElement(ap.getListaClientes().get(i).getListCarros().get(j));
//                    }
//                }
//            }
//            CB_CARS.setModel(modelo2);
//        }
    }//GEN-LAST:event_CB_CarOwnersItemStateChanged

    private void CB_CarOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_CarOwnersActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_CARS.getModel();
        Cliente temp
                = (Cliente) CB_CarOwners.getSelectedItem();
        if (temp != null) {
            System.out.println("HELLLOO  ONE");
            bitacora1 ap = new bitacora1("./Cliente.cbm");
            ap.cargarArchivo();
            for (int i = 0; i < ap.getListaClientes().size(); i++) {
                System.out.println("IS IT HERE");
                if (temp.getName().equals(ap.getListaClientes().get(i).getName())) {
                    System.out.println("HELLOOOOO INSIDE IFFFF");
                    //ap.getListaClientes().get(i).getListCarros();
                    for (int j = 0; j < ap.getListaClientes().get(i).getListCarros().size(); j++) {
                        System.out.println("INSIDE SECOND IF");
                        modelo2.addElement(ap.getListaClientes().get(i).getListCarros().get(j));
                    }
                }
            }
            CB_CARS.setModel(modelo2);
        }

    }//GEN-LAST:event_CB_CarOwnersActionPerformed

    private void JB_SaveToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveToEmployeeActionPerformed
        // TODO add your handling code here:
         Empleado temp
                = (Empleado) CB_CarsToEmployee.getSelectedItem();
          if (temp != null) {
            bitacora2 ap = new bitacora2("./Empleado.cbm");
            ap.cargarArchivo();
            for (int i = 0; i < ap.getListaEmpleados().size(); i++) {
                System.out.println("IS IT HERE");
                if (temp.getNombre().equals(ap.getListaEmpleados().get(i).getNombre())) {
                    System.out.println("HELLOOOOO INSIDE IFFFF");
                    //ap.getListaClientes().get(i).getListCarros();
                    for (int j = 0; j < ap.getListaEmpleados().get(i).getListCarros().size(); j++) {
                        System.out.println("INSIDE SECOND IF");
                        //modelo2.addElement(ap.getListaClientes().get(i).getListCarros().get(j));
                    }
                }
            }
          }
         

    }//GEN-LAST:event_JB_SaveToEmployeeActionPerformed

    private void JB_SimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SimulacionActionPerformed
        // TODO add your handling code here:
        TH1.start();
        TH2.start();
        TH3.start();
    }//GEN-LAST:event_JB_SimulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Lab7().setVisible(true);
            }
        });
    }
    Thread1 TH1;
    Thread2 TH2;
    Thread3 TH3;
    int cont = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_CARS;
    private javax.swing.JComboBox<String> CB_CarOwners;
    private javax.swing.JComboBox<String> CB_CarsToBeAdded;
    private javax.swing.JComboBox<String> CB_CarsToEmployee;
    private javax.swing.JComboBox<String> CB_Clientes;
    private javax.swing.JComboBox<String> CB_Empleado1;
    private javax.swing.JComboBox<String> CB_Empleado2;
    private javax.swing.JComboBox<String> CB_Empleado3;
    private javax.swing.JComboBox<String> CB_Size;
    private javax.swing.JButton JB_AddingCarToClient;
    private javax.swing.JButton JB_CreateCarro;
    private javax.swing.JButton JB_FinishCliente;
    private javax.swing.JButton JB_SaveCliente;
    private javax.swing.JButton JB_SaveEmpleado;
    private javax.swing.JButton JB_SaveToEmployee;
    private javax.swing.JButton JB_Simulacion;
    private javax.swing.JDialog JD_AddCarsToClient;
    private javax.swing.JDialog JD_AddClienteCarsToEmployee;
    private javax.swing.JDialog JD_CrearCarro;
    private javax.swing.JDialog JD_CrearCliente;
    private javax.swing.JDialog JD_RegistrarEmpleado;
    private javax.swing.JMenuItem JMI_AddingCarToEmployee;
    private javax.swing.JMenuItem JMI_AddingCarTooClient;
    private javax.swing.JMenuItem JMI_CreateCar;
    private javax.swing.JMenuItem JMI_CreateClient;
    private javax.swing.JMenuItem JMI_CreateEmployee;
    private javax.swing.JProgressBar JProgressBar_Empleado1;
    private javax.swing.JProgressBar JProgressBar_Empleado2;
    private javax.swing.JProgressBar JProgressBar_Empleado3;
    private javax.swing.JSpinner JSpinner_DoorCant;
    private javax.swing.JSpinner JSpinner_Empleado;
    private javax.swing.JSpinner JSpinner_LevelDirty;
    private javax.swing.JSpinner JSpinner_edadCliente;
    private javax.swing.JTextField JT_ApellidoCliente;
    private javax.swing.JTextField JT_ApellidoEmpleado;
    private javax.swing.JTextField JT_NameCliente;
    private javax.swing.JTextField JT_NameEmpleado;
    private javax.swing.JTextField JT_NumeroPlaca;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanel_CrearCliente;
    private javax.swing.JPanel MainPanel_JFrame;
    private javax.swing.JPanel MainPanel_RegistrarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
